---
title: "Clustering and Dimensionality Reduction"
author: "Abed Kurdi and David Wu"
---

Set working directory to project directory
```{r setup}
require(knitr)
opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())
```

### Optionally convert this Rmd to R script 
```{r eval=FALSE, message=FALSE}
current_file <- rstudioapi::getActiveDocumentContext()$path
output_file <- stringr::str_replace(current_file, '.Rmd', '.R')
knitr::purl(current_file, output = output_file)
file.edit(output_file)
```

### Directories
```{r, message=FALSE}
output_dir <- 'analysis/output/02_cluster' # analysis file output directory
data_dir <- 'data/derived/seurat' # data file output directory

dir.create(output_dir, showWarnings = FALSE)
dir.create(data_dir, showWarnings = FALSE)
```

### Loading the libraries
```{r, message=FALSE}
library(Seurat) 
library(tidyverse)
library(ggExtra)
library(openxlsx)
library(harmony)
library(SeuratWrappers)
library(wutilities)
library(tictoc)
```


```{r, message=FALSE}
# library(metap) 
# library(MAST) 
# 
# library(ggplot2) 
# library(cowplot) 
# library(patchwork) 
# library(writexl)
# library(dplyr)

# library(harmony)

# library(rgl)
# library(ggExtra)
# library(ggplotify)
```

```{r}
seuratobj <- read_rds(file.path(data_dir, 'seuratobj_merged.rds'))
seuratobj
```

### Run Harmony
```{r}
seuratobj <- seuratobj %>% 
    RunHarmony(c("treatment", "chemistry"), 
               plot_convergence = TRUE, 
               assay.use = 'RNA')
```

### Make the elbow plot
```{r}
pdf(paste0(output_dir,"elbow_plot.pdf"))
ElbowPlot(seuratobj, ndims=30, reduction = 'harmony')
dev.off()
```

### RunUMAP, FindNeighbors and FindClusters using resolutions starting from 0.1 to 2, by 0.1
```{r}
seuratobj <- seuratobj %>% 
    RunUMAP(reduction = "harmony", dims = 1:20, assay="RNA") %>% 
    FindNeighbors(reduction = "harmony", dims = 1:20, assay="RNA") %>% 
    FindClusters(resolution = seq(0.1, 2, by = 0.1), graph.name = "RNA_snn")
```
### Visualize
```{r}
p <- seurat_feature(seuratobj, features = c('RNA_snn_res.0.2'), facet_hide = TRUE, legend_position = 'none', title = 'Resolution: 0.2')
ggsave(plot = p,
       filename = 'umap_res_0.2.png',
       h = 5,
       w = 5,
       dpi = 150,
       path = file.path(output_dir, 'umap'))
p
```
```{r}

p <- seurat_feature(seuratobj, features = c('RNA_snn_res.1'), facet_hide = TRUE, color_package = 'ggplot', legend_position = 'none', title = 'Resolution: 1.0')

ggsave(plot = p,
       filename = 'umap_res_1.0.png',
       h = 5,
       w = 5,
       dpi = 150,
       path = file.path(output_dir, 'umap'))
p
```

## Export
```{r}
seuratobj %>% write_rds(file.path(data_dir, 'seuratobj_clustered.rds'))
```

## Session Info
```{r}
sessionInfo()
```



