---
title: "ADT Analysis"
author: "David Wu"
---

### Use the here package for robust relative paths
```{r}
library(here)
```

### Optionally convert this Rmd to R script 
```{r eval=FALSE, message=FALSE}
current_file <- rstudioapi::getActiveDocumentContext()$path
output_file <- stringr::str_replace(current_file, '.Rmd', '.R')
knitr::purl(current_file, output = output_file)
file.edit(output_file)
```

### Directories
```{r, message=FALSE}
output_dir <- here('analysis/output/04_adt') # analysis file output directory
data_dir <- here('data/derived/tildra') # data file output directory

dir.create(output_dir, showWarnings = FALSE)
dir.create(data_dir, showWarnings = FALSE)
```

### Load libraries
```{r, message=FALSE}
library(Seurat) 
library(tidyverse)
library(ggExtra)
library(harmony)
library(SeuratWrappers)
library(wutilities) # devtools::install_github('symbiologist/wutilities')
library(tictoc)
theme_set(theme_dwu()) # set default theme
```

### Load Seurat object
```{r}
seuratobj <- read_rds(here(data_dir, 'seuratobj_clustered.rds'))
metadata <- seuratobj@meta.data %>% rownames_to_column() %>% as_tibble()
seuratobj
```
### Analysis
#### ADT colnames
```{r}
adt_markers <- seuratobj@assays$ADT %>% rownames()
adt_markers
```
```{r}
seurat_feature(seuratobj, features = c('ADT_CD4'))
```
```{r}
VlnPlot(seuratobj, features = c('ADT_CD4'), group.by = 'id', pt.size = 0.1)
```
#### Which samples have mouse cells?
```{r}
metadata %>% 
  filter(species == 'Mouse' | adt == 'Yes') %>% 
  select(id, sample, mouse, adt) %>% 
  unique()
```
```{r}
adt_samples <- metadata %>% filter(adt == 'Yes') %>% pull(id) %>% unique()
```

### Calling ADT
```{r}
adt_data <- FetchData(seuratobj, vars = c('id', 'adt', 'species', paste0('ADT_', adt_markers))) %>% 
  rownames_to_column() %>% 
  filter(adt == 'Yes') %>% 
  pivot_longer(cols = starts_with('ADT_'),
               names_to = 'marker',
               values_to = 'expression') %>% 
  mutate(marker = str_remove(marker, 'ADT_')) %>% 
  select(-adt)

adt_data %>% head()
```

```{r}
plot_dir <- here(output_dir, 'histograms')

map(adt_markers, function(i) {
  
  sample_subset <- adt_data %>% 
    filter(marker == i)
  
  p <- sample_subset %>% 
    ggplot(aes(x = expression,
               fill = species)) +
    geom_histogram(bins = 100) +
    rcartocolor::scale_fill_carto_d() +
    facet_wrap(~id, scales = 'free') +
    theme(legend.position = 'top') +
    labs(x = 'Normalized Expression',
         y = '# of Cells',
         title = i)
  
  ggsave(plot = p,
         filename = paste0(i, '.png'),
         path = plot_dir,
         h = 12,
         w = 12)
  
})


```

## Export
```{r}

```

## Session Info
```{r}
sessionInfo()
```



