---
title: "Clustering and Dimensionality Reduction"
author: "Abed Kurdi and David Wu"
---

### Use the here package for robust relative paths
```{r}
library(here)
```

### Optionally convert this Rmd to R script 
```{r eval=FALSE, message=FALSE}
current_file <- rstudioapi::getActiveDocumentContext()$path
output_file <- stringr::str_replace(current_file, '.Rmd', '.R')
knitr::purl(current_file, output = output_file)
file.edit(output_file)
```

### Directories
```{r, message=FALSE}
output_dir <- here('analysis/output/04_cluster') # analysis file output directory
data_dir <- here('data/derived/tildra') # data file output directory

dir.create(output_dir, showWarnings = FALSE)
dir.create(data_dir, showWarnings = FALSE)
```

### Load libraries
```{r, message=FALSE}
library(Seurat) 
library(tidyverse)
library(ggExtra)
library(SeuratWrappers)
library(wutilities) # devtools::install_github('symbiologist/wutilities')
library(tictoc)
library(harmony)
theme_set(theme_dwu()) # set default theme
```

### Load Seurat object
```{r}
seuratobj <- read_rds(file.path(data_dir, 'seuratobj_qc.rds'))
seuratobj
```

### Removal of mouse cells and genes
```{r}
seuratobj <- seuratobj %>% subset(subset = species == 'Human', features = str_subset(rownames(seuratobj), 'mm10---', negate = TRUE))
seuratobj
```
### Incorporate ADT calls
```{r}
adt <- read_tsv(here('analysis/output/03_adt/adt_calls.tsv.gz'))

metadata_to_add <- seuratobj@meta.data %>% 
  rownames_to_column() %>% 
  select(rowname) %>% 
  left_join(adt) %>% 
  column_to_rownames('rowname')

colnames(metadata_to_add) <- paste0('ADT.', colnames(metadata_to_add))

seuratobj <- Seurat::AddMetaData(seuratobj, metadata = metadata_to_add)

```

### Normalization and PCA
```{r}
seuratobj <- seuratobj %>% 
  NormalizeData() %>%
  ScaleData() %>% 
  FindVariableFeatures() %>% 
  RunPCA() 
```

### Run Harmony
```{r}
seuratobj <- seuratobj %>% 
  RunHarmony(group.by.vars = c('treatment', 'chemistry', 'patient', 'flow', 'mouse'), 
             plot_convergence = TRUE, 
             assay.use = 'RNA')
```

### Make the elbow plot
```{r}
pdf(here(output_dir, "elbow_plot.pdf"))
ElbowPlot(seuratobj, ndims = 30, reduction = 'harmony')
dev.off()
```

### RunUMAP, FindNeighbors, and FindClusters 
```{r}
dims <- 1:20

seuratobj <- seuratobj %>% 
    RunUMAP(reduction = "harmony", dims = dims, assay = "RNA") %>% 
    FindNeighbors(reduction = "harmony", dims = dims, assay = "RNA") %>% 
    FindClusters(resolution = c(0.2, 1, 2))
```

### Set default cluster resolution
```{r}
### Fix cluster factor levels
clusterings <- colnames(seuratobj@meta.data) %>% str_subset('_res')

for(i in clusterings) {
  clusters <- seuratobj@meta.data[[i]]
  seuratobj[[i]] <- factor(clusters, levels = levels(clusters) %>% as.numeric() %>% sort())
}

Idents(seuratobj) <- 'RNA_snn_res.0.2'
```


### Visualize
```{r}
p <- seurat_feature(seuratobj, features = c('RNA_snn_res.0.2'), facet_hide = TRUE, legend_position = 'none', title = 'Resolution: 0.2')
ggsave(plot = p,
       filename = 'umap_res_0.2.png',
       h = 5,
       w = 5,
       dpi = 300,
       path = here(output_dir, 'umap'))
p
```
```{r}
p <- seurat_feature(seuratobj, features = c('RNA_snn_res.1'), facet_hide = TRUE, color_package = 'ggplot', legend_position = 'none', title = 'Resolution: 1.0')

ggsave(plot = p,
       filename = 'umap_res_1.0.png',
       h = 5,
       w = 5,
       dpi = 300,
       path = here(output_dir, 'umap'))
p
```
```{r}
p <- seurat_feature(seuratobj, features = c('RNA_snn_res.1'), 
                    facet_hide = TRUE, 
                    color_package = 'generate', 
                    color_palette = 'custom1', 
                    legend_position = 'right', 
                    title = 'Resolution: 1.0')

p
```

## Export
```{r}
seuratobj %>% write_rds(here(data_dir, 'seuratobj_clustered.rds'))
```

## Session Info
```{r}
sessionInfo()
```



