---
title: "Annotation"
author: "David Wu"
---

Set working directory to project directory
```{r setup}
require(knitr)
opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())
```

### Optionally convert this Rmd to R script 
```{r eval=FALSE, message=FALSE}
current_file <- rstudioapi::getActiveDocumentContext()$path
output_file <- stringr::str_replace(current_file, '.Rmd', '.R')
knitr::purl(current_file, output = output_file)
file.edit(output_file)
```

### Directories
```{r, message=FALSE}
output_dir <- 'analysis/output/05_annotate' # analysis file output directory
data_dir <- 'data/derived/seurat' # data file output directory

dir.create(output_dir, showWarnings = FALSE)
dir.create(data_dir, showWarnings = FALSE)
```

### Loading the libraries
```{r, message=FALSE}
library(Seurat) 
library(tidyverse)
library(ggExtra)
library(SeuratWrappers)
library(wutilities) # devtools::install_github('symbiologist/wutilities')
library(tictoc)
library(googlesheets4)
```

```{r}
seuratobj <- read_rds(file.path(data_dir, 'seuratobj_subcluster.rds'))
seuratobj
```
### Import annotation table
```{r}
annotations <- read_sheet('https://docs.google.com/spreadsheets/d/1pLMOaXkSGq3qSX7bTIw2daWd3ItA5JxqFomQn_km1IU/edit#gid=0') %>% 
  filter(!is.na(cluster)) %>% 
  mutate(cluster = factor(cluster))

annotations$label <- factor(annotations$label, levels = annotations$label)
annotations
```
### Ensure factor level ordering
```{r}
levels(annotations$label)
```

#### Get current clusters and integrate with annotations
```{r}
cluster_annotation <- seuratobj@meta.data %>% 
  select(cluster = seurat_clusters) %>% 
  rownames_to_column() %>% 
  left_join(annotations %>% select(cluster, label)) %>% 
  column_to_rownames('rowname')
cluster_annotation
```

```{r}
seuratobj <- AddMetaData(seuratobj, cluster_annotation)
Idents(seuratobj) <- 'label'
Idents(seuratobj) %>% head()
```

### Export
```{r}
seuratobj@meta.data %>% rownames_to_column() %>% write_tsv(file.path(output_dir, 'metadata.tsv.gz'))
seuratobj %>% write_rds(file.path(data_dir, 'seuratobj_annotated.rds'))
```


## Session Info
```{r}
sessionInfo()
```



