---
title: "DE analysis"
author: "David Wu"
---

Set working directory to project directory
```{r setup}
require(knitr)
opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())
```

### Optionally convert this Rmd to R script 
```{r eval=FALSE, message=FALSE}
current_file <- rstudioapi::getActiveDocumentContext()$path
output_file <- stringr::str_replace(current_file, '.Rmd', '.R')
knitr::purl(current_file, output = output_file)
file.edit(output_file)
```

### Directories
```{r, message=FALSE}
output_dir <- 'analysis/output/07_de' # analysis file output directory
data_dir <- 'data/derived/seurat' # data file output directory

dir.create(output_dir, showWarnings = FALSE)
dir.create(data_dir, showWarnings = FALSE)
```

### Loading the libraries
```{r, message=FALSE}
library(Seurat) 
library(tidyverse)
library(ggExtra)
library(SeuratWrappers)
library(wutilities) # devtools::install_github('symbiologist/wutilities')
library(tictoc)
library(openxlsx)
```

```{r}
seuratobj <- read_rds(file.path(data_dir, 'seuratobj_annotated.rds'))
meta <- seuratobj@meta.data %>% rownames_to_column()
seuratobj
```
### Proportion of cells in each cluster
```{r}
analyze <- meta %>% 
  select(rowname, id, sample, condition, treatment, cluster, merged_label) %>% 
  mutate(description = factor(paste(condition, treatment) %>% str_remove(' None'),
                              levels = c('PV Pre',
                                         'PV Post',
                                         'PV',
                                         'AD',
                                         'HC')))

analyze %>% head()
```

```{r}
plot_input <- analyze %>% 
  group_by(description, cluster, merged_label) %>% 
  tally() %>% 
  group_by(merged_label) %>% 
  mutate(total = sum(n),
         fraction = n/total)

plot_input
```

```{r}
p <- plot_input %>% 
  ggplot(aes(x = merged_label,
             y = fraction,
             fill = description)) +
  geom_bar(stat = 'identity',
           position = 'stack') +
  coord_flip() +
  rcartocolor::scale_fill_carto_d(palette = 'Bold') +
  labs(x = '',
       y = 'Proportion')

ggsave(plot = p,
       filename = 'bar_percentages.png',
       path = output_dir,
       h = 6,
       w = 8)

p
```


### Comparisons per cluster functions
```{r}
de_pipeline <- function(seuratobj,
                        cluster,
                        condition1,
                        condition2,
                        treatment1,
                        treatment2,
                        comparison,
                        exclude_id = NULL,
                        min.pct = 0.01,
                        logfc.threshold = log2(1.1),
                        test.use = 'Presto') {
  
   metadata <- seuratobj@meta.data %>% rownames_to_column()
  
  if(comparison == 'condition') {
    group1_id <- paste0(condition1, collapse = '_')
    group2_id <- paste0(condition2, collapse = '_')
  } else {
    group1_id <- treatment1
    group2_id <- treatment2
  }
  
  group1 <- metadata %>% 
    filter(merged_label == {{cluster}},
           condition %in% condition1,
           treatment %in% treatment1) %>% 
    pull(rowname)
  
  group2 <- metadata %>% 
    filter(merged_label == {{cluster}},
           condition %in% condition2,
           treatment %in% treatment2) %>% 
    pull(rowname)
  
  n_group1 <- length(group1)
  n_group2 <- length(group2)
  
  if(test.use == 'Presto') {
    
    de_genes <- RunPresto(object = seuratobj, 
                            ident.1 = group1,
                            ident.2 = group2, 
                            min.pct = min.pct,
                            logfc.threshold = logfc.threshold)
    
  } else {
    
    de_genes <- FindMarkers(object = seuratobj, 
                            ident.1 = group1,
                            ident.2 = group2, 
                            min.pct = min.pct,
                            logfc.threshold = logfc.threshold,
                            test.use = test.use) 
   
  }
  
  de_genes %>%
    rownames_to_column('gene') %>% 
    mutate(pct.diff = pct.1 - pct.2,
           cluster = cluster,
           group1 = group1_id,
           group2 = group2_id,
           n_group1 = n_group1,
           n_group2 = n_group2) %>% 
    select(cluster, gene, group1, group2, n_group1, n_group2, everything())

}

de_pipeline_barcodes <- function(seuratobj,
                                 cluster,
                                 barcodes1,
                                 barcodes2,
                                 group1_id,
                                 group2_id,
                                 exclude_id = NULL,
                                 min.pct = 0.01,
                                 logfc.threshold = log2(1.1),
                                 test.use = 'Presto') {
  
  metadata <- seuratobj@meta.data %>% rownames_to_column() %>% filter(rowname %in% c(barcodes1, barcodes2))
  
  n_group1 <- length(barcodes1)
  n_group2 <- length(barcodes2)
  
  if(test.use == 'Presto') {
    
    de_genes <- RunPresto(object = seuratobj, 
                            ident.1 = barcodes1,
                            ident.2 = barcodes2, 
                            min.pct = min.pct,
                            logfc.threshold = logfc.threshold)
    
  } else {
    
    de_genes <- FindMarkers(object = seuratobj, 
                            ident.1 = barcodes1,
                            ident.2 = barcodes2, 
                            min.pct = min.pct,
                            logfc.threshold = logfc.threshold,
                            test.use = test.use) 
   
  }
  
  de_genes %>%
    rownames_to_column('gene') %>% 
    mutate(pct.diff = pct.1 - pct.2,
           cluster = cluster,
           group1 = group1_id,
           group2 = group2_id,
           n_group1 = n_group1,
           n_group2 = n_group2) %>% 
    select(cluster, gene, group1, group2, n_group1, n_group2, everything())

}

write_excel_notebook <- function(input_table, output_file, tabs = 'cluster', prefix = 'cluster_') {
  OUT <- createWorkbook()
  
  input_table$tabs <- input_table[[tabs]]
  tabs <- input_table[[tabs]] %>% unique()
  
  
  for(i in tabs){
    tryCatch({
      table_subset <- input_table %>% filter(tabs == i)
      
      sheet_name <- paste0(prefix, i) %>% str_remove('[\\?/]') %>% str_remove('[\\/]')
      addWorksheet(OUT, sheet_name)
      writeData(OUT, sheet = sheet_name, x = table_subset)
      
    }, error=function(e){message(paste0("We have an error here in ", i))})
  }
  
  saveWorkbook(OUT, output_file, overwrite = TRUE)
}
```

```{r}
patient_meta <- meta %>% 
  select(id, sample, treatment, condition, response) %>% 
  unique()

patient_meta
```

### AD vs HC (11 v 11)
```{r}
condition1 <- 'AD'
condition2 <- 'HC'
treatment1 <- 'None'
treatment2 <- 'None'
comparison <- 'condition'

clusters_ad_vs_hc <- analyze %>% 
  filter(condition %in% c(condition1, condition2),
         treatment %in% c(treatment1, treatment2)) %>% 
  group_by(merged_label, condition, treatment, id) %>% 
  tally() %>% 
  filter(n > 10) %>% # at least 10 cells per sample
  group_by(merged_label, condition, treatment) %>% 
  tally() %>% 
  filter(n > 3) %>% # at least 3 samples per comparison group
  select(merged_label, all_of(comparison)) %>% 
  unique() %>% 
  group_by(merged_label) %>% 
  tally() %>% 
  filter(n > 1)

de_ad_vs_hc <- map(clusters_ad_vs_hc$merged_label, function(i) {
  
  de_pipeline(seuratobj = seuratobj,
              cluster = i, 
              comparison = comparison,
              condition1 = condition1,
              condition2 = condition2,
              treatment1 = treatment1,
              treatment2 = treatment2) 
  
}) %>% 
  bind_rows()

de_ad_vs_hc %>% write_tsv(file.path(output_dir, 'de_ad_vs_hc.tsv.gz'))

write_excel_notebook(input_table = de_ad_vs_hc,
                     output_file = file.path(output_dir, 'de_ad_vs_hc.xlsx'))

de_ad_vs_hc %>% head()
```

### PV vs HC (13 v 11)
```{r}
condition1 <- 'PV'
condition2 <- 'HC'
treatment1 <- c('None', 'Pre')
treatment2 <- 'None'
comparison <- 'condition'

clusters_pv_vs_hc <- analyze %>% 
  filter(condition %in% c(condition1, condition2),
         treatment %in% c(treatment1, treatment2)) %>% 
  group_by(merged_label, condition, treatment, id) %>% 
  tally() %>% 
  filter(n > 10) %>% # at least 10 cells per sample
  group_by(merged_label, condition, treatment) %>% 
  tally() %>% 
  filter(n > 3) %>% # at least 3 samples per comparison group
  select(merged_label, all_of(comparison)) %>% 
  unique() %>% 
  group_by(merged_label) %>% 
  tally() %>% 
  filter(n > 1)


de_pv_vs_hc <- map(clusters_pv_vs_hc$merged_label, function(i) {
  
  print2(i)
  de_pipeline(seuratobj = seuratobj,
              cluster = i, 
              comparison = comparison,
              condition1 = condition1,
              condition2 = condition2,
              treatment1 = treatment1,
              treatment2 = treatment2) 
  
}) %>% bind_rows()

de_pv_vs_hc %>% write_tsv(file.path(output_dir, 'de_pv_vs_hc.tsv.gz'))

write_excel_notebook(input_table = de_pv_vs_hc,
                     output_file = file.path(output_dir, 'de_pv_vs_hc.xlsx'))

de_pv_vs_hc %>% head()


```


### PV+AD vs HC (24 v 11)
```{r}
condition1 <- c('AD', 'PV')
condition2 <- 'HC'
treatment1 <- c('None', 'Pre')
treatment2 <- 'None'
comparison <- 'condition'

clusters_adpv_vs_hc <- analyze %>% 
  filter(condition %in% c(condition1, condition2),
         treatment %in% c(treatment1, treatment2)) %>% 
  group_by(merged_label, condition, treatment, id) %>% 
  tally() %>% 
  filter(n > 10) %>% # at least 10 cells per sample
  group_by(merged_label, condition, treatment) %>% 
  tally() %>% 
  filter(n > 3) %>% # at least 3 samples per comparison group
  select(merged_label, all_of(comparison)) %>% 
  unique() %>% 
  group_by(merged_label) %>% 
  tally() %>% 
  filter(n > 2)


de_adpv_vs_hc <- map(clusters_adpv_vs_hc$merged_label, function(i) {
  
  print2(i)
  de_pipeline(seuratobj = seuratobj,
              cluster = i, 
              comparison = comparison,
              condition1 = condition1,
              condition2 = condition2,
              treatment1 = treatment1,
              treatment2 = treatment2) 
  
}) %>% bind_rows()

de_adpv_vs_hc %>% write_tsv(file.path(output_dir, 'de_adpv_vs_hc.tsv.gz'))

write_excel_notebook(input_table = de_adpv_vs_hc,
                     output_file = file.path(output_dir, 'de_adpv_vs_hc.xlsx'))

de_adpv_vs_hc %>% head()
```

### PV vs AD (13 v 11)
```{r}
condition1 <- 'AD'
condition2 <- 'PV'
treatment1 <- 'None'
treatment2 <- c('None', 'Pre')
comparison <- 'condition'

clusters_ad_vs_pv <- analyze %>% 
  filter(condition %in% c(condition1, condition2),
         treatment %in% c(treatment1, treatment2)) %>% 
  group_by(merged_label, condition, treatment, id) %>% 
  tally() %>% 
  filter(n > 10) %>% # at least 10 cells per sample
  group_by(merged_label, condition, treatment) %>% 
  tally() %>% 
  filter(n > 3) %>% # at least 3 samples per comparison group
  select(merged_label, all_of(comparison)) %>% 
  unique() %>% 
  group_by(merged_label) %>% 
  tally() %>% 
  filter(n > 1)


de_ad_vs_pv <- map(clusters_ad_vs_pv$merged_label, function(i) {
  
  print2(i)
  de_pipeline(seuratobj = seuratobj,
              cluster = i, 
              comparison = comparison,
              condition1 = condition1,
              condition2 = condition2,
              treatment1 = treatment1,
              treatment2 = treatment2) 
  
}) %>% bind_rows()

de_ad_vs_pv %>% write_tsv(file.path(output_dir, 'de_ad_vs_pv.tsv.gz'))
write_excel_notebook(input_table = de_ad_vs_pv,
                     output_file = file.path(output_dir, 'de_ad_vs_pv.xlsx'))

de_ad_vs_pv %>% head() 


```


### Pre vs Post 
```{r}
condition1 <- 'PV'
condition2 <- 'PV'
treatment1 <- 'Pre'
treatment2 <- 'Post'
comparison <- 'treatment'

clusters_pre_vs_post <- analyze %>% 
  filter(condition %in% c(condition1, condition2),
         treatment %in% c(treatment1, treatment2)) %>% 
  group_by(merged_label, condition, treatment, id) %>% 
  tally() %>% 
  filter(n > 10) %>% # at least 10 cells per sample
  group_by(merged_label, condition, treatment) %>% 
  tally() %>% 
  filter(n > 3) %>% # at least 3 samples per comparison group
  select(merged_label, all_of(comparison)) %>% 
  unique() %>% 
  group_by(merged_label) %>% 
  tally() %>% 
  filter(n > 1)


de_pre_vs_post <- map(clusters_pre_vs_post$merged_label, function(i) {
  
  print2(i)
  de_pipeline(seuratobj = seuratobj,
              cluster = i, 
              comparison = comparison,
              condition1 = condition1,
              condition2 = condition2,
              treatment1 = treatment1,
              treatment2 = treatment2) 
   
}) %>% bind_rows()

de_pre_vs_post %>% write_tsv(file.path(output_dir, 'de_pre_vs_post.tsv.gz'))
write_excel_notebook(input_table = de_pre_vs_post,
                     output_file = file.path(output_dir, 'de_pre_vs_post.xlsx'))

de_pre_vs_post %>% head()


```
```{r}
condition1 <- 'PV'
condition2 <- 'PV'
treatment1 <- 'Pre'
treatment2 <- 'Post'
comparison <- 'treatment'

patients <- patient_meta %>% 
  filter(treatment %in% c(treatment1, treatment2)) %>% 
  separate(sample, into = c('patient', NA)) %>% 
  pivot_wider(names_from = treatment, values_from = id)

de_pre_vs_post <- map(patients$patient, function(i) {
  
  print2(i)
  de_pipeline(seuratobj = seuratobj,
              cluster = i, 
              comparison = comparison,
              condition1 = condition1,
              condition2 = condition2,
              treatment1 = treatment1,
              treatment2 = treatment2) 
  
  
   
}) %>% bind_rows()

de_pre_vs_post %>% write_tsv(file.path(output_dir, 'de_pre_vs_post.tsv.gz'))
write_excel_notebook(input_table = de_pre_vs_post,
                     output_file = file.path(output_dir, 'de_pre_vs_post.xlsx'))

de_pre_vs_post %>% head()

```

### Combined DE table
```{r}
list(de_ad_vs_hc,
     de_pv_vs_hc,
     de_adpv_vs_hc,
     de_ad_vs_pv,
     de_pre_vs_post) %>% 
  bind_rows() %>% 
  mutate(comparison = paste(group1, 'vs', group2)) %>% 
  select(comparison, everything()) %>% 
  write_tsv(file.path(output_dir, 'de_combined.tsv.gz'))
```


### Per sample analysis of Trm
```{r}
condition1 <- 'PV'
condition2 <- 'PV'
treatment1 <- 'Pre'
treatment2 <- 'Post'
comparison <- 'treatment'

patients <- patient_meta %>% 
  filter(treatment %in% c(treatment1, treatment2)) %>% 
  separate(sample, into = c('patient', NA)) %>% 
  pivot_wider(names_from = treatment, values_from = id)

cluster <- 'Trm_merge'

de_pre_vs_post_patients <- map(patients$patient, function(i) {
  
  single_patient <- patients %>% filter(patient == i)
  response <- single_patient$response
  cluster_subset <- meta %>% filter(merged_label == {{cluster}})
  pre_barcodes <- cluster_subset %>% filter(id == single_patient$Pre) %>% pull(rowname)
  post_barcodes <- cluster_subset %>% filter(id == single_patient$Post) %>% pull(rowname)
  
  print2(i)
  de_pipeline_barcodes(seuratobj = seuratobj,
                       cluster = cluster, 
                       barcodes1 = pre_barcodes,
                       barcodes2 = post_barcodes,
                       group1_id = paste0(i, '_Pre'),
                       group2_id = paste0(i, '_Post')) %>% 
    mutate(patient = i,
           response = response) %>% 
    select(patient, response, everything())
  
  
   
}) %>% bind_rows()
```


```{r}
de_pre_vs_post_patients %>% write_tsv(file.path(output_dir, 'de_pre_vs_post_patients.tsv.gz'))
write_excel_notebook(input_table = de_pre_vs_post_patients,
                     output_file = file.path(output_dir, 'de_pre_vs_post_patients.xlsx'),
                     tabs = 'patient',
                     prefix = 'patient_')



```

### responders vs non-responders
```{r}
condition1 <- 'PV'
condition2 <- 'PV'
treatment1 <- 'Pre'
treatment2 <- 'Post'
comparison <- 'treatment'

patients <- patient_meta %>% 
  filter(treatment %in% c(treatment1, treatment2)) %>% 
  separate(sample, into = c('patient', NA)) %>% 
  pivot_wider(names_from = treatment, values_from = id)

cluster <- 'Trm_merge'

de_pre_vs_post_response <- map(c('responders', 'non-responders'), function(i) {
  
  if(i == 'responders') {
    patient_subset <- patients %>% filter(response %in% c('full'))  
  } else {
    patient_subset <- patients %>% filter(response %in% c('partial', 'failure'))  
  }
  
  cluster_subset <- meta %>% filter(merged_label == {{cluster}})
  
  pre_barcodes <- cluster_subset %>% filter(id %in% patient_subset$Pre) %>% pull(rowname)
  post_barcodes <- cluster_subset %>% filter(id %in% patient_subset$Post) %>% pull(rowname)
  
  print2(i)
  de_pipeline_barcodes(seuratobj = seuratobj,
                       cluster = cluster, 
                       barcodes1 = pre_barcodes,
                       barcodes2 = post_barcodes,
                       group1_id = paste0(i, '_Pre'),
                       group2_id = paste0(i, '_Post')) %>% 
    mutate(response = i) %>% 
    select(response, everything())
  
}) %>% bind_rows()

de_pre_vs_post_response %>% write_tsv(file.path(output_dir, 'de_pre_vs_post_response.tsv.gz'))
write_excel_notebook(input_table = de_pre_vs_post_response,
                     output_file = file.path(output_dir, 'de_pre_vs_post_response.xlsx'),
                     tabs = 'response',
                     prefix = '')
```

## Session Info
```{r}
sessionInfo()
```



