---
title: "Parameter Tuning"
author: "David Wu"
---

### Use the here package for robust relative paths
```{r}
library(here)
```

### Optionally convert this Rmd to R script 
```{r eval=FALSE, message=FALSE}
current_file <- rstudioapi::getActiveDocumentContext()$path
output_file <- stringr::str_replace(current_file, '.Rmd', '.R')
knitr::purl(current_file, output = output_file)
file.edit(output_file)
```

### Directories
```{r, message=FALSE}
output_dir <- 'analysis/output/parameters' # analysis file output directory
data_dir <- 'data/derived/tildra' # data file output directory

dir.create(output_dir, showWarnings = FALSE)
dir.create(data_dir, showWarnings = FALSE)
```

### Loading the libraries
```{r, message=FALSE}
library(Seurat) 
library(tidyverse)
library(wutilities) # devtools::install_github('symbiologist/wutilities')
library(tictoc)
theme_set(wutilities::theme_dwu())
```

### Import
#### Clustered object
```{r}
seuratobj <- read_rds(here(data_dir, 'seuratobj_annotated.rds'))
seuratobj
```

### Explore data
```{r}
ElbowPlot(seuratobj, ndims = 50)
```
### Quick clustering and visualization
```{r eval = FALSE}
max_dims <- 10
seuratobj <- FindNeighbors(seuratobj, reduction = 'harmony', dims = 1:max_dims)
seuratobj <- FindClusters(seuratobj, resolution = 0.2)
seuratobj <- RunUMAP(seuratobj, n.neighbors = 30, reduction = 'harmony', dims = 1:max_dims)

p <- seurat_plot(seuratobj, reduction = 'umap', feature = 'ident', color_package = 'carto', color_scale = 'Bold', size = 0.5, alpha = 0.5, do.label = T, show.legend = F)

p
```

## Parameter testing
### Parameters
```{r}
# output_directory
output_dir <- 'analysis/meninges/scrna/output/06_clustering_parameters'
dir.create(file.path(output_dir, 'plots'), recursive = TRUE)

# global params
reduction <- 'harmony'
w <- 5
h <- 5
dpi <- 150
type <- '.png'

# clustering params
dims <- c(10, 20, 30)
cluster_neighbors <- c(20, 30, 50)

# clustering resolution
resolution <- 0.2

# umap params
umap_neighbors <- c(30, 50)
min_dist <- c(0.1, 0.2, 0.3) 
iterations <- c(250)

# trials per parameter set
trial <- 1

combinations <- crossing(
  'dims' = dims,
  'cluster_neighbors' = cluster_neighbors,
  'resolution' = resolution,
  'umap_neighbors' = umap_neighbors,
  'min_dist' = min_dist,
  'iterations' = iterations,
  'trial' = trial) %>% 
  mutate(id = 1:n()) %>% 
  select(id, everything())

combinations %>% write_tsv(file.path(output_dir, 'parameters.tsv'))
combinations
```
### Parameters for testing
```{r}
i <- 10
j <- 20
k <- 0.2
l <- 30
m <- 0.1
n <- 250
o <- 1
```

```{r}
map(dims, function(i) {
  map(cluster_neighbors, function(j) {
    
    test_subset <- seuratobj %>% FindNeighbors(reduction = reduction, dims = 1:j, k.param = i) 
    
    map(resolution, function(k) {
      
      test_subset <- test_subset %>% FindClusters(resolution = resolution)
      
      map(umap_neighbors, function(l) {
        map(min_dist, function(m) {
          map(iterations, function(n) {
            map(trial, function(o) {
              
              random_seed <- sample(seq(as.Date('2019-01-01'), as.Date('2022-12-31'), by = 'day'), 1) %>% as.character() %>% str_remove_all('-') %>% as.numeric()
              
              parameters <- combinations %>% 
                filter(dims == i,
                       cluster_neighbors == j,
                       resolution == k,
                       umap_neighbors == l,
                       min_dist == m,
                       iterations == n,
                       trial == o) %>% 
                mutate(seed = random_seed)
              
              parameter_set <- parameters %>% pull(id)
              
              cat(crayon::red(paste('Running parameter set', parameter_set, 'of', max(combinations$id), '\n')))
              
              test_subset <- RunUMAP(test_subset, 
                                     n.neighbors = l, 
                                     min.dist = m,
                                     n.epochs = n,
                                     n.components = 2,
                                     dims = 1:j,
                                     reduction = reduction,
                                     seed.use = random_seed)
              
              umap <- seurat_plot(test_subset, 
                                  reduction = 'umap', 
                                  do.label = T, 
                                  feature = 'seurat_clusters', 
                                  color_package = 'carto', color_scale = 'Bold',
                                  size = 0.2) 
              
              # using gridExtra
              p_params <- tableGrob(parameters %>% t())
              p_output <- grid.arrange(umap, p_params, ncol = 2)

              ggsave(plot = p_output, filename = paste0(output_dir, '/plots/', parameter_set, type), width = w * 2, height = h, dpi = dpi)
              
            })
          })
        })
      })
    })
  })
})
rm(test_subset)
gc()
Sys.time()
```




## Session info
```{r}
sessionInfo()
```

