---
title: "Python libraries"
author: "David Wu"
---

```{r}
file.edit('~/.Renviron')
```


```{r}
#Sys.setenv(RETICULATE_PYTHON='/home/dwu/.virtualenvs/seurat/bin/python')
library(reticulate)
use_virtualenv('seurat')
py_config()
py_install('umap-learn')
py_module_available('umap')
```
```{python}
import umap
```

```{r}
Sys.setenv(RETICULATE_PYTHON='/home/dwu/.virtualenvs/seurat/bin/python')
library(reticulate)
#use_python('/home/dwu/miniconda3/envs/seurat/bin/python')
use_condaenv('seurat')
```

```{r}
virtualenv_list()
```

```{r}
virtualenv_create('seurat')
```

```{r}
py_list_packages()
```
```{r}
py_module_available('umap-learn')
```


```{r}
```

https://github.com/conda/conda/issues/11366
```{bash}
CONDA_OVERRIDE_CUDA=10.2 conda install -n base -c conda-forge libffi
```

### Setup python libraries
```{r}
library(reticulate)
#Sys.setenv(RETICULATE_PYTHON = '~/.virtualenvs/seurat/bin/python')
#use_virtualenv('~/.virtualenvs/seurat/')
py_config()
#reticulate::use_python('/home/dwu/miniconda3/envs/seuratenv/bin/python')
```
```{r}
virtualenv_create('seurat')
use_virtualenv('seurat')
```

```{r}
py_install('umap-learn')
```

```{r}
py_module_available('umap-learn')
```

```{r}
use_virtualenv('seurat')
```


```{r}
virtualenv_create('seurat')
```

```{r}
virtualenv_install('seurat', 'umap-learn')
```

```{r}

```

```{r}
py_config()
py_install('umap-learn')
#use_condaenv('seuratenv')
conda_install('r-reticulate', 'umap-learn')
import('umap-learn')
py_module_available('umap-learn')
```

