---
title: "RashX dataset"
author: "David Wu"
---

### Use the here package for robust relative paths
```{r}
library(here)
```

### Optionally convert this Rmd to R script 
```{r eval=FALSE, message=FALSE}
current_file <- rstudioapi::getActiveDocumentContext()$path
output_file <- stringr::str_replace(current_file, '.Rmd', '.R')
knitr::purl(current_file, output = output_file)
file.edit(output_file)
```

### Directories
```{r, message=FALSE}
output_dir <- 'analysis/output/rashx' # analysis file output directory
data_dir <- 'data/derived/tildra' # data file output directory

dir.create(output_dir, showWarnings = FALSE)
```

### Load libraries
```{r, message=FALSE}
library(Seurat) 
library(tidyverse)
library(SeuratWrappers)
library(wutilities)
library(tictoc)
```

### Import
RashX Seurat object from https://zenodo.org/record/6471748
```{r}
seuratobj <- read_rds(here('data/external/rashx.rds'))
metadata <- seuratobj@meta.data %>% rownames_to_column() %>% as_tibble()
seuratobj
```
```{r}
sample_info <- metadata %>% 
  select(ident, donor, dis, treat, STATUS) %>% 
  unique()
sample_info
```
### Retrieve barcodes
#### Duplicated cells
```{r}
duplicates <- metadata %>% 
  separate(rowname, sep = '_', into = c('celltype', 'barcode', 'sample', 'sample_id'), remove = FALSE) %>% 
  group_by(barcode, orig.ident) %>% add_count() %>% filter(n > 1) %>% arrange(orig.ident, barcode)
duplicates
```
```{r}
to_remove <- duplicates %>% filter(celltype == 'Cell cycle') %>% pull(rowname)
```

#### Prepare clustering data and add supercluster
```{r}
rashx_clusters <- metadata %>% 
  filter(!(rowname %in% to_remove)) %>% 
  separate(rowname, sep = '_', into = c('celltype', 'barcode', 'sample', 'sample_id'), remove = FALSE) %>% 
  mutate(id = str_remove(ident, 'kin'),
         supercluster = str_remove(Ident2, '[:digit:]|-c')) %>% # add supercluster
  select(barcode, 
         id,
         cluster = Ident2, 
         supercluster) 

rashx_clusters 
```

```{r}
rashx_clusters %>% select(cluster, supercluster) %>% unique() %>% arrange(supercluster)
```

## Export
```{r}
rashx_clusters %>% write_tsv(here(output_dir, 'rashx_clusters.tsv.gz'))

subset(seuratobj, cells = c(colnames(seuratobj) %>% setdiff(to_remove))) %>% 
  write_rds(here('data/external/rashx_clean.rds'))
```
## Session Info
```{r}
sessionInfo()
```



