---
title: "Template"
author: "David Wu"
output: html_notebook
---
## Purpose
Template

## Setup
Set working directory to project directory
```{r setup}
require(knitr)
opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())
```

### Optionally convert this Rmd to R script 
```{r eval=FALSE, message=FALSE}
current_file <- rstudioapi::getActiveDocumentContext()$path
output_file <- stringr::str_replace(current_file, '.Rmd', '.R')
knitr::purl(current_file, output = output_file)
file.edit(output_file)
```

### Load custom themes and functions
```{r, message=FALSE}
source('analysis/scripts/themes.R') # themes for all project components

#source('analysis/scripts/functions.R') # custom functions for all project components

theme_set(theme_publication()) # set default theme
```

### Directories
```{r, message=FALSE}
analysis_dir <- 'analysis/output/' # analysis file output directory
data_dir <- 'data/' # data file output directory

dir.create(analysis_dir, showWarnings = FALSE)
dir.create(data_dir, showWarnings = FALSE)
```

### Load libraries
```{r, message=FALSE}
library(tidyverse)
```

### Import files
```{r}

```


## Analysis

```{r}

```


## Session info
```{r}
sessionInfo()
```

