---
title: "Annotation"
author: "David Wu"
---

### Use the here package for robust relative paths
```{r}
library(here)
```

### Optionally convert this Rmd to R script 
```{r eval=FALSE, message=FALSE}
current_file <- rstudioapi::getActiveDocumentContext()$path
output_file <- stringr::str_replace(current_file, '.Rmd', '.R')
knitr::purl(current_file, output = output_file)
file.edit(output_file)
```

### Directories
```{r, message=FALSE}
output_dir <- 'analysis/output/06_annotate' # analysis file output directory
data_dir <- 'data/derived/tildra' # data file output directory

dir.create(output_dir, showWarnings = FALSE)
dir.create(data_dir, showWarnings = FALSE)
```

### Loading the libraries
```{r, message=FALSE}
library(Seurat) 
library(tidyverse)
library(ggExtra)
library(SeuratWrappers)
library(wutilities) # devtools::install_github('symbiologist/wutilities')
library(tictoc)
library(googlesheets4)
library(ggsankey)
library(aricode)
library(SingleR)
theme_set(wutilities::theme_dwu())
```

### Functions
```{r}
calculate_agreement <- function(group1,
                                group2) {
  
  tibble('AMI' = aricode::AMI(group1, group2),
         'ARI' = aricode::ARI(group1, group2))
  
}

```

### Import
#### Clustered object
```{r}
seuratobj <- read_rds(here(data_dir, 'seuratobj_subcluster.rds'))
metadata <- seuratobj@meta.data %>% rownames_to_column()

seuratobj
```

#### Import annotations from RashX paper
```{r}
rashx <- read_rds(here('data/external/rashx.rds'))
rashx
```

```{r}
ref <- subset(rashx, downsample = 400) 
query <- subset(seuratobj, downsample = 400)
```


```{r}
tic()
anchors <- FindTransferAnchors(reference = ref, 
                               query = query,
                               dims = 1:20, 
                               features = VariableFeatures(query),
                               reduction = 'pcaproject')

predictions <- TransferData(anchorset = anchors,
                            refdata = ref$Ident2,
                            dims = 1:20)

toc()
```


```{r}
tic()

toc()

predictions
```

```{r}
query <- AddMetaData(query, metadata = predictions)
```
```{r}
p <- query %>% seurat_feature(features = 'predicted.id', legend_position = 'none', color_package = 'carto', color_palette = 'Bold')
p
```

```{r}
compare_id <- query@meta.data %>% select(predicted.id, global, local, global_cluster)
compare_id
```

```{r}
p_sankey <- compare_id %>% filter(local == 'L0') %>%  plot_sankey1(nodes = c('local', 'predicted.id'), top_n = 44, percentages = TRUE)
p_sankey
```

```{r}
p_sankey <- compare_id %>% filter(global_cluster == 'Trm1') %>%  plot_sankey1(nodes = c('global_cluster', 'predicted.id'), top_n = 44, percentages = TRUE)
p_sankey
```
```{r}
p_sankey <- compare_id %>% filter(local == 'L0') %>%  plot_sankey1(nodes = c('local', 'predicted.id'), top_n = 44, percentages = TRUE)
p_sankey
```

```{r}
library(SingleCellExperiment)
library(scuttle)
library(SingleR)
library(scRNAseq)



sce_rashx <- SingleCellExperiment(list(counts = sce1_input@assays$RNA@counts),
                                  colData = DataFrame(label = as.character(sce1_input$Ident2) %>% str_replace('[/-]', '_'))) %>% 
  logNormCounts()

sce_obj <- SingleCellExperiment(list(counts = sce2_input@assays$RNA@counts),
                                colData = DataFrame(cluster = as.character(sce2_input$global))) %>% 
  logNormCounts()
```


```{r}
sce_rashx
```

```{r}
singler <- SingleR(test = sce_obj,
                   ref = sce_rashx,
                   labels = sce_rashx$label,
                   de.method = 'wilcox')
```

```{r}
singler
```

### Load scibet library
```{r}
library(scibet)
```

### Prepare input
#### WARNING: required >160 GB RAM when densifying sparse matrices
```{r}
shared_genes <- intersect(rownames(seuratobj), rownames(rashx))

tic()
ref_input <- rashx@assays$RNA@data[shared_genes, ] %>% as.matrix() %>% t() %>% as.data.frame()
ref_input <- cbind(ref_input, 'label' = rashx$Ident2)
query_input <- seuratobj@assays$RNA@data[shared_genes, ] %>% as.matrix() %>% t() %>% as.data.frame()
toc()
```
### Label transfer
```{r}
tic()
prd <- SciBet(train = ref_input,
              test = query_input, 
              k = 3000)

seuratobj$label <- prd
toc()
```


```{r}
p1 <- seurat_feature(seuratobj, features = 'label', facet_hide = TRUE, color_package = 'carto', color_palette = 'Bold', rasterize_dpi = 600, legend_position = 'none')

ggsave(plot = p1,
       filename = 'umap_label.png',
       path = output_dir,
       dpi = 600,
       w = 5, 
       h = 5)

p1
```

```{r}
p2 <- seurat_feature(seuratobj, features = 'local', facets = 'label', facet_hide = FALSE, color_package = 'carto', color_palette = 'Bold', label = FALSE, legend_position = 'none', rasterize_dpi = 600)

ggsave(plot = p2,
       filename = 'umap_label_facets.png',
       path = output_dir,
       dpi = 600,
       w = 10, 
       h = 10)
p2
```
### Export
```{r}
seuratobj@meta.data %>% rownames_to_column() %>% select(rowname, label) %>% write_tsv(here(output_dir, 'labels.tsv.gz'))
```
