---
title: "Unified Clustering and Dimensionality Reduction"
author: "David Wu"
---

### Use the here package for robust relative paths
```{r}
library(here)
```

### Optionally convert this Rmd to R script 
```{r eval=FALSE, message=FALSE}
current_file <- rstudioapi::getActiveDocumentContext()$path
output_file <- stringr::str_replace(current_file, '.Rmd', '.R')
knitr::purl(current_file, output = output_file)
file.edit(output_file)
```

### Directories
```{r, message=FALSE}
data_dir <- here('data/derived/tildra') # data file output directory
```


### Load libraries
```{r, message=FALSE}
library(Seurat) 
library(tidyverse)
library(wutilities) # devtools::install_github('symbiologist/wutilities')
library(tictoc)
library(harmony)
theme_set(theme_dwu()) # set default theme
```

### Load Seurat object
```{r}
seuratobj <- read_rds(file.path(data_dir, 'seuratobj_qc.rds')) %>% subset(subset = species == 'Human', features = str_subset(rownames(.), 'mm10---', negate = TRUE))
seuratobj
```

```{r}
sampling <- colnames(seuratobj) %>% sample(size = 50000)
seuratobj <- subset(seuratobj, cells = sampling)

dims <- 1:15
neighbors <- 30
metric <- 'cosine'

seuratobj <- seuratobj %>% 
  NormalizeData() %>%
  ScaleData() %>% 
  FindVariableFeatures(nfeatures = 2000) %>% 
  RunPCA() %>%
  FindNeighbors(dims = dims, k.param = neighbors, annoy.metric = metric)
```

### Usual method
```{r}
method1 <- seuratobj %>% FindClusters(resolution = 0.1) 
method1 <- method1 %>% RunUMAP(dims = dims)

p1 <- seurat_feature(method1)
p1
```
```{r}
seurat_feature(method1, facets = 'seurat_clusters', label = FALSE)
```
### Manual UWOT
```{r}
reduction <- seuratobj@reductions$pca@cell.embeddings[, dims]

uwot_manual <- uwot::umap(X = reduction, 
                          n_neighbors = neighbors,
                          metric = metric, 
                          n_epochs = 200, 
                          learning_rate = 1, 
                          min_dist = 0.3, 
                          spread = 1, 
                          set_op_mix_ratio = 1, 
                          local_connectivity = 1, 
                          repulsion_strength = 1,
                          negative_sample_rate = 5,
                          verbose = TRUE)


method1[['uwot']] <- CreateDimReducObject(embeddings = uwot_manual, key = 'UWOT_', assay = 'RNA')
```


```{r}
p_manual <- seurat_feature(method1, reduction = 'uwot')
p_manual
```
```{r}
seurat_feature(method1, reduction = 'uwot', facets = 'seurat_clusters', label = FALSE)
```


#### Method 2
```{r}
method2 <- seuratobj %>% FindNeighbors(dims = dims, k.param = neighbors, annoy.metric = metric, return.neighbor = TRUE, force.recalc = TRUE)

nn_object <- method2@neighbors$RNA.nn

seurat_nn <- list('idx' = nn_object@nn.idx, 
                  'dist' = nn_object@nn.dist)


uwot_provide_nn <- uwot::umap(X = reduction, 
                              nn_method = seurat_nn,
                              metric = metric, 
                              n_epochs = 200, 
                              learning_rate = 1, 
                              min_dist = 0.3, 
                              spread = 1, 
                              set_op_mix_ratio = 1, 
                              local_connectivity = 1, 
                              repulsion_strength = 1,
                              negative_sample_rate = 5,
                              verbose = TRUE)

method1[['uwot_nn']] <- CreateDimReducObject(embeddings = uwot_provide_nn, key = 'UWOTnn_', assay = 'RNA')
                              
                              

p2 <- seurat_feature(method1, reduction = 'uwot_nn')

p2
```

```{r}
 seurat_feature(method1, reduction = 'uwot_nn', facets = 'seurat_clusters', label=FALSE)
```
### Method 3
Use uwot nn for clustering
```{r}

uwot_get_nn <- uwot::umap(X = reduction, 
                          metric = 'cosine', 
                          n_epochs = 200, 
                          learning_rate = 1, 
                          min_dist = 0.3, 
                          spread = 1, 
                          set_op_mix_ratio = 1, 
                          local_connectivity = 1, 
                          repulsion_strength = 1,
                          negative_sample_rate = 5, 
                          ret_nn = TRUE)

uwot_nn <- uwot_get_nn$nn$cosine

method2@neighbors$RNA.nn@nn.idx <- uwot_nn$idx
method2@neighbors$RNA.nn@nn.dist <- uwot_nn$dist

method3 <- method2 %>% FindNeighbors(k.param = 30)
```

