---
title: "Figure 5"
author: "David Wu"
---

### Use the here package for robust relative paths
```{r}
library(here)
```

### Optionally convert this Rmd to R script 
```{r eval=FALSE, message=FALSE}
current_file <- rstudioapi::getActiveDocumentContext()$path
output_file <- stringr::str_replace(current_file, '.Rmd', '.R')
knitr::purl(current_file, output = output_file)
file.edit(output_file)
```

### Directories
```{r, message=FALSE}
output_dir <- here('figures/figure5') # analysis file output directory
data_dir <- here('data/derived/tildra') # data file output directory

dir.create(output_dir, showWarnings = FALSE)
dir.create(data_dir, showWarnings = FALSE)
```

### Loading the libraries
```{r, message=FALSE}
library(Seurat) 
library(tidyverse)
library(ggExtra)
library(ggthemes)
library(ggforce)
library(patchwork)
library(wutilities) # devtools::install_github('symbiologist/wutilities')
library(tictoc)
library(rcartocolor)
library(ggrepel)
library(extrafont)
loadfonts()
theme_set(theme_dwu()) # set default theme
source(here('figures/colors.R')) # consistent color palettes

```

### Import Visium object and add metadata
```{r}
seuratobj <- read_rds(here(data_dir, 'visium_integrated.rds'))
seuratobj
```

```{r}
genes <- c('CD3D', 'KRT1', 'COL1A1', 'PECAM1')

p1 <- SpatialPlot(seuratobj, images = 'P8Mid', alpha = c(0, 1)) +
  ggtitle('Biopsy')
p2 <- map(genes, function(i) {
  SpatialFeaturePlot(seuratobj,
                          features = i,
                          image.alpha = 0,
                          images = 'P8Mid') +
    ggtitle(i) + NoLegend()
})

p <- p1 + p2[1] + p2[2] + p2[3] + p2[4] + plot_layout(nrow = 1)

ggsave(plot = p,
       path = output_dir,
       device = cairo_pdf,
       h = 2,
       w = 8,
       filename = 'F4A.pdf')
p
```
Legend
```{r}
p <- SpatialFeaturePlot(seuratobj,
                        features = 'COL1A1',
                        image.alpha = 0,
                        images = 'P8Mid') +
  theme(legend.position = 'right')

ggsave(plot = p,
       path = output_dir,
       device = cairo_pdf,
       h = 2,
       w = 2,
       filename = 'F4A_legend.pdf')

p
```

